# FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:optimism
FROM ghcr.io/concrete-eth/archetype/example:latest

RUN apk add --no-cache jq

COPY entrypoint-l2.sh /entrypoint.sh

VOLUME ["/db"]

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
